/*
  Auto-generated by Spline
*/

import useSpline from '@splinetool/r3f-spline'
// import { OrthographicCamera } from '@react-three/drei'

export default function Scene({ ...props }) {
  const { nodes, materials } = useSpline('https://prod.spline.design/8PMhQ-xuGCnAWzmc/scene.splinecode')
  return (
    <>
      <color attach="background" args={['#a59393']} />
      <group {...props} dispose={null}>
        <scene name="Scene 1">
          <mesh
            name="Sphere 3"
            geometry={nodes['Sphere 3'].geometry}
            material={materials['Sphere 3 Material']}
            castShadow
            receiveShadow
            position={[45.16, 30.42, 31.23]}
            rotation={[-Math.PI / 2, 0, -Math.PI / 2]}
          />
          <mesh
            name="Sphere 2"
            geometry={nodes['Sphere 2'].geometry}
            material={materials['Sphere 2 Material']}
            castShadow
            receiveShadow
            position={[45.16, 30.42, 0.37]}
            rotation={[-Math.PI / 2, 0, -Math.PI / 2]}
          />
          <mesh
            name="Sphere1"
            geometry={nodes.Sphere1.geometry}
            material={materials['Sphere1 Material']}
            castShadow
            receiveShadow
            position={[45.16, 30.42, -32.16]}
            rotation={[-Math.PI / 2, 0, -Math.PI / 2]}
          />
        </scene>
      </group>
    </>
  )
}
