/*
  Auto-generated by Spline
*/

import useSpline from '@splinetool/r3f-spline'
import { OrthographicCamera } from '@react-three/drei'

export default function Frog({ ...props }) {
  const { nodes, materials } = useSpline('https://prod.spline.design/1vFpLuZBjCqcxKso/scene.splinecode')
  return (
    <>
      <color attach="background" args={['#74757a']} />
      <group {...props} dispose={null}>
        <scene name="Scene 1">
          <group name="Frog" position={[0, 51.37, 0]}>
            <mesh
              name="Sphere 5"
              geometry={nodes['Sphere 5'].geometry}
              material={materials['Sphere 5 Material']}
              castShadow
              receiveShadow
              position={[-41.49, 88.82, 23.64]}
              rotation={[0, 0.21, 0.02]}
              scale={1}
            />
            <mesh
              name="Sphere 4"
              geometry={nodes['Sphere 4'].geometry}
              material={materials['Sphere 4 Material']}
              castShadow
              receiveShadow
              position={[41.66, 88.32, 23.75]}
              rotation={[0, 0.21, 0.02]}
              scale={1}
            />
            <mesh
              name="Sphere 3"
              geometry={nodes['Sphere 3'].geometry}
              material={materials['Sphere 3 Material']}
              castShadow
              receiveShadow
              position={[-37.84, 87.45, 12.29]}
            />
            <mesh
              name="Sphere 2"
              geometry={nodes['Sphere 2'].geometry}
              material={materials['Sphere 2 Material']}
              castShadow
              receiveShadow
              position={[39.84, 87.45, 12.29]}
            />
            <mesh
              name="Sphere"
              geometry={nodes.Sphere.geometry}
              material={materials['Sphere Material']}
              castShadow
              receiveShadow
              position={[0, 41.42, 0]}
              rotation={[-Math.PI / 2, 0, 0]}
            />
            <group name="Body Instance" position={[-0.87, -46.43, 0]}>
              <mesh
                name="Body"
                geometry={nodes.Body.geometry}
                material={nodes.Body.material}
                castShadow
                receiveShadow
                position={[0, 2.19, 0]}
              />
            </group>
          </group>
          <group name="Body1" position={[-0.87, 4.94, 0]}>
            <mesh
              name="Body2"
              geometry={nodes.Body2.geometry}
              material={nodes.Body2.material}
              castShadow
              receiveShadow
              position={[0, 2.19, 0]}
            />
          </group>
          <directionalLight
            name="Directional Light"
            castShadow
            intensity={0.7}
            shadow-mapSize-width={1024}
            shadow-mapSize-height={1024}
            shadow-camera-near={-10000}
            shadow-camera-far={100000}
            shadow-camera-left={-1000}
            shadow-camera-right={1000}
            shadow-camera-top={1000}
            shadow-camera-bottom={-1000}
            position={[256.25, 300, 149.56]}
            rotation={[0, 0.57, 0]}
          />
          <OrthographicCamera name="1" makeDefault={true} far={10000} near={-50000} />
          <hemisphereLight name="Default Ambient Light" intensity={0.75} color="#eaeaea" />
        </scene>
      </group>
    </>
  )
}
