/*
This file was generated by https://github.com/pmndrs/gltfjsx and then
customized manually. It uses drei's new useAnimations hook which extracts
all actions and sets up a THREE.AnimationMixer for it so that you don't have to.
All of the assets actions, action-names and clips are available in its output. 
*/

import React, { useEffect, useState, useMemo } from "react"
import { useFBX } from "@react-three/drei";


export default function Model({ ...props }) {
    const fbx = useFBX("Cow.fbx");

    return (
        <>
          <group {...props} dispose={null}>
            <primitive object={fbx} scale={0.01} />;
          </group>
        </>
      )
}
